image:
  file: .cde.Dockerfile

tasks:
  - name: Azure CLI
    command: |
      sh ./cde/azure_sp.sh
      gp sync-done waitonazurecli
  - name: Azure Storage
    command: |
      gp sync-await waitonazurecli
      sh ./cde/storage.sh
      gp sync-done waitonnstate
  - name: Terraform
    command: |
      gp sync-await waitonnstate
      sh ./cde/terraform.sh
      cd terraform


vscode:
  extensions:
    - hashicorp.terraform